### ISSUE TITLE
🐛 ValueError: no index available for pileup

### ISSUE THREAD

**Issue by Wytamma** [mjsull/qhery#2]
I'm getting this error when I try to run `qhery` with a BAM file. Do I need to have an index in the same location as the BAM file?

```
Could not retrieve index file for '2022-112557.bam'
Traceback (most recent call last):
  File "/home/wwirth/.conda/envs/qhery/bin/qhery", line 8, in <module>
    sys.exit(main())
  File "/home/wwirth/.conda/envs/qhery/lib/python3.9/site-packages/qhery/__main__.py", line 121, in main
    make_output.make_final_tables(mut_list_sample, gt.resistances, mut_list_var, gt.epitopes, args.pipeline_dir, args.sample_name, args.bam, aa_to_nuc_dict)
  File "/home/wwirth/.conda/envs/qhery/lib/python3.9/site-packages/qhery/make_output.py", line 73, in make_final_tables
    codon_usage, codon_depth = get_codons(bam_file, aa_to_nuc_dict[gene][start])
  File "/home/wwirth/.conda/envs/qhery/lib/python3.9/site-packages/qhery/make_output.py", line 226, in get_codons
    for pileupcolumn in samfile.pileup("MN908947.3", start_position):
  File "pysam/libcalignmentfile.pyx", line 1340, in pysam.libcalignmentfile.AlignmentFile.pileup
ValueError: no index available for pileup
```

**Comment by mjsull** [comment]
Qhery will now return an error if you provide it with an unindexed BAM file.
