### ISSUE TITLE
Consensus sequence 

### ISSUE THREAD

**Issue by Wytamma** [mjsull/qhery#3]
Is is possible to use a consensus sequence with qhery? Is it valid to produce a VCF from the consensus and use that?

**Comment by Wytamma** [comment]
I've tried using `--fasta` however the `.bcftools.vcf` file cannot be parsed. 

```
[E::bcf_hdr_parse_sample_line] Could not parse the "#CHROM.." line, either the fields are incorrect or spaces are present instead of tabs:
        #CHROM  POS     ID      REF     ALT     QUAL    FILTER

Failed to read from qhery_output/2022-086840/2022-086840.bcftools.vcf: could not parse header
Traceback (most recent call last):
  File "/home/wwirth/.conda/envs/qhery/bin/qhery", line 8, in <module>
    sys.exit(main())
  File "/home/wwirth/.conda/envs/qhery/lib/python3.9/site-packages/qhery/__main__.py", line 110, in main
    mut_list_sample = mf.parse_csq()
  File "/home/wwirth/.conda/envs/qhery/lib/python3.9/site-packages/qhery/get_mutants.py", line 71, in parse_csq
    with codecs.open(csq_file, 'r', encoding='utf-8', errors='ignore') as f:
  File "/home/wwirth/.conda/envs/qhery/lib/python3.9/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'qhery_output/2022-086840/2022-086840.csq.tsv'
```

**Comment by mjsull** [comment]
Qhery has been updated to run nextclade and use the output for variant calls and variant assignment.
