### ISSUE TITLE
ValueError: not enough values to unpack (expected 7, got 5)

### ISSUE THREAD

**Issue by Wytamma** [mjsull/qhery#6]
Some of my VCF files don't have every element in the `Consequence` column. E.g. for the start_loss mutations...

```
CSQ	-	-	MN908947.3	27395	start_lost|ORF7a|ENSSAST00005000009|protein_coding|+
```

Thus, `prot_mut` and `nuc_mut` are not returned from `consequence.split("|")`.

```
Traceback (most recent call last):
  File "/home/wwirth/.conda/envs/qhery/bin/qhery", line 8, in <module>
    sys.exit(main())
  File "/home/wwirth/.conda/envs/qhery/lib/python3.9/site-packages/qhery/__main__.py", line 114, in main
    mut_list_sample = mf.parse_csq()
  File "/home/wwirth/.conda/envs/qhery/lib/python3.9/site-packages/qhery/get_mutants.py", line 76, in parse_csq
    mut_type, gene, acc, gene_type, strand, prot_mut, nuc_mut = consequence.split("|")
ValueError: not enough values to unpack (expected 7, got 5)
```

**Comment by Wytamma** [comment]
Fixed in #7
